object DependencyVersions {
    const val androidxJunitVersion = "1.1.5"
    const val composeNavVersion = "2.5.3"
    const val datastorePreferencesVersion = "1.0.0"
    const val detektVersion = "1.22.0"
    const val espressoCoreVersion = "3.5.1"
    const val hiltVersion = "2.45"
    const val junitVersion = "4.13.2"
    const val kotlinVersion = "1.8.20"
    const val mockkVersion = "1.13.3"
    const val pagingVersion = "3.1.1"
    const val playServicesLocationVersion = "21.0.1"
    const val roomVersion = "2.5.1"
    const val twitterComposeRulesVersion = "0.0.26"
}

object DependencyNames {
    const val androidxJunit = "androidx.test.ext:junit:${DependencyVersions.androidxJunitVersion}"
    const val datastorePreferences = "androidx.datastore:datastore-preferences:${DependencyVersions.datastorePreferencesVersion}"
    const val detektFormatting = "io.gitlab.arturbosch.detekt:detekt-formatting:${DependencyVersions.detektVersion}"
    const val espressoCore = "androidx.test.espresso:espresso-core:${DependencyVersions.espressoCoreVersion}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${DependencyVersions.hiltVersion}"
    const val hiltAndroidCompiler = "com.google.dagger:hilt-android-compiler:${DependencyVersions.hiltVersion}"
    const val hiltAndroidGradlePlugin = "com.google.dagger:hilt-android-gradle-plugin:${DependencyVersions.hiltVersion}"
    const val hiltAndroidTesting = "com.google.dagger:hilt-android-testing:${DependencyVersions.hiltVersion}"
    const val hiltCompiler = "com.google.dagger:hilt-compiler:${DependencyVersions.hiltVersion}"
    const val junit = "junit:junit:${DependencyVersions.junitVersion}"
    const val mockk = "io.mockk:mockk:${DependencyVersions.mockkVersion}"
    const val mockkAgent = "io.mockk:mockk-agent:${DependencyVersions.mockkVersion}"
    const val mockkAndroid = "io.mockk:mockk-android:${DependencyVersions.mockkVersion}"
    const val navigationCompose = "androidx.navigation:navigation-compose:${DependencyVersions.composeNavVersion}"
    const val pagingCommon = "androidx.paging:paging-common:${DependencyVersions.pagingVersion}"
    const val playServicesLocation = "com.google.android.gms:play-services-location:${DependencyVersions.playServicesLocationVersion}"
    const val roomCompiler = "androidx.room:room-compiler:${DependencyVersions.roomVersion}"
    const val roomKtx = "androidx.room:room-ktx:${DependencyVersions.roomVersion}"
    const val roomPaging = "androidx.room:room-paging:${DependencyVersions.roomVersion}"
    const val roomRuntime = "androidx.room:room-runtime:${DependencyVersions.roomVersion}"
    const val twitterComposeRulesDetekt = "com.twitter.compose.rules:detekt:${DependencyVersions.twitterComposeRulesVersion}"
}
